version: '3'
services:
  neo4j:
    image: neo4j:5.19
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=neo4j/neo4j2025

  springboot-app:
    image: openjdk:17-jdk-slim
    ports:
      - "8080:8080"
    volumes:
      - ./app:/app
    command: ["java", "-jar", "/app/graph8Rop-0.0.1-SNAPSHOT.jar"]
    environment:
      - SPRING_NEO4J_URI=bolt://neo4j:7687
      - SPRING_NEO4J_AUTHENTICATION_USERNAME=neo4j
      - SPRING_NEO4J_AUTHENTICATION_PASSWORD=neo4j2025

